version: '3'

services:
  # Node.js backend service
  nodejs-backend:
    build:
      context: ./PhotoTube-Server  # Path to your Node.js backend folder
    ports:
      - "1324:1324"
    environment:
      - NODE_ENV=production
      - TCP_SERVER_HOST=cpp-tcp-server  # Use the service name of the TCP server container
      - TCP_SERVER_PORT=2347
    networks:
      - app-network

  # React frontend service
  react-frontend:
    build:
      context: ./PhotoTube-Web  # Path to your React frontend folder
    ports:
      - "3000:3000"
    networks:
      - app-network

  # C++ TCP server service (running in a container)
  cpp-tcp-server:
    build:
      context: ./PhotoTube-TCP-Server  # Path to your C++ TCP server folder
    ports:
      - "2347:2347"  # Expose the TCP server port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
